---
- name: Build & Push Images
  hosts: localhost
  gather_facts: no
  tags:
    - build
  tasks:
    - name: Build docker images
      shell: "docker build -t {{ docker_registry }}/{{ item }} -f {{ item }}.Dockerfile ."
      args:
        chdir: "{{ playbook_dir }}/docker"
      with_items:
        - caddy
        - php
      register: docker_build
      changed_when: "'Successfully tagged' in docker_build.stdout"
    
    - name: Push to registry
      shell: "docker push {{ docker_registry }}/{{ item }}"
      with_items:
        - caddy
        - php
      register: docker_push
      when: "docker_build | changed"
      changed_when: "'latest: digest: ' in docker_push.stdout"

- name: Deploy Services
  hosts: docker_swarm_manager
  run_once: yes
  become: yes
  gather_facts: no
  tags:
    - update
  tasks:
    - name: Create placeholder for compose file
      file:
        path: "{{ project_path }}"
        state: directory
    
    - name: Create docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: "{{ project_path }}/docker-compose.yml"
    
    - name: Run stack deploy
      shell: "docker stack deploy -c {{ project_path }}/docker-compose.yml {{ project_name }}"
      register: docker_stack_deploy
    
    - name: Deploy output
      debug:
        var: docker_stack_deploy.stdout_lines

