- name: Create volume on all node
  hosts: docker_swarm_manager,docker_swarm_worker
  become: True
  tasks:
    - name: ensure volume directories existed on all swarm nodes
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/gitlab-runner
        

- name: Create CI/CD Stack
  hosts: docker_swarm_manager
  run_once: True
  become: True
  vars:
    - stack_name: gitlab-runner
  tasks:

    - name: Create tmpfile for stack definition file
      tempfile:
        suffix: _stack.yml
      register: stack_yml_tempfile

    - name: Upload stack definition
      copy:
        src: "files/stack/gitlab-runner.yml"
        dest: "{{ stack_yml_tempfile.path }}"

    - name: Deploy stack
      shell: "docker stack deploy -c {{ stack_yml_tempfile.path }} {{ stack_name }}"

    # - name: cleaning
    #   file:
    #     path: "{{ stack_yml_tempfile.path }}"
    #     state: absent
